# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mirmik/project/radioline/rfmeask

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mirmik/project/radioline/rfmeask

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	cd /home/mirmik/project/radioline/rfmeask && $(CMAKE_COMMAND) -E cmake_progress_start /home/mirmik/project/radioline/rfmeask/CMakeFiles /home/mirmik/project/radioline/rfmeask/submodules/rabbit/CMakeFiles/progress.marks
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f CMakeFiles/Makefile2 submodules/rabbit/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mirmik/project/radioline/rfmeask/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f CMakeFiles/Makefile2 submodules/rabbit/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f CMakeFiles/Makefile2 submodules/rabbit/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f CMakeFiles/Makefile2 submodules/rabbit/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/mirmik/project/radioline/rfmeask && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
submodules/rabbit/CMakeFiles/rabbit.dir/rule:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f CMakeFiles/Makefile2 submodules/rabbit/CMakeFiles/rabbit.dir/rule
.PHONY : submodules/rabbit/CMakeFiles/rabbit.dir/rule

# Convenience name for target.
rabbit: submodules/rabbit/CMakeFiles/rabbit.dir/rule

.PHONY : rabbit

# fast build rule for target.
rabbit/fast:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit.dir/build.make submodules/rabbit/CMakeFiles/rabbit.dir/build
.PHONY : rabbit/fast

# Convenience name for target.
submodules/rabbit/CMakeFiles/rabbit_test.dir/rule:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f CMakeFiles/Makefile2 submodules/rabbit/CMakeFiles/rabbit_test.dir/rule
.PHONY : submodules/rabbit/CMakeFiles/rabbit_test.dir/rule

# Convenience name for target.
rabbit_test: submodules/rabbit/CMakeFiles/rabbit_test.dir/rule

.PHONY : rabbit_test

# fast build rule for target.
rabbit_test/fast:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/build
.PHONY : rabbit_test/fast

rabbit/intersect.o: rabbit/intersect.cpp.o

.PHONY : rabbit/intersect.o

# target to build an object file
rabbit/intersect.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit.dir/build.make submodules/rabbit/CMakeFiles/rabbit.dir/rabbit/intersect.cpp.o
.PHONY : rabbit/intersect.cpp.o

rabbit/intersect.i: rabbit/intersect.cpp.i

.PHONY : rabbit/intersect.i

# target to preprocess a source file
rabbit/intersect.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit.dir/build.make submodules/rabbit/CMakeFiles/rabbit.dir/rabbit/intersect.cpp.i
.PHONY : rabbit/intersect.cpp.i

rabbit/intersect.s: rabbit/intersect.cpp.s

.PHONY : rabbit/intersect.s

# target to generate assembly for a file
rabbit/intersect.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit.dir/build.make submodules/rabbit/CMakeFiles/rabbit.dir/rabbit/intersect.cpp.s
.PHONY : rabbit/intersect.cpp.s

rabbit/space/screw.o: rabbit/space/screw.cpp.o

.PHONY : rabbit/space/screw.o

# target to build an object file
rabbit/space/screw.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit.dir/build.make submodules/rabbit/CMakeFiles/rabbit.dir/rabbit/space/screw.cpp.o
.PHONY : rabbit/space/screw.cpp.o

rabbit/space/screw.i: rabbit/space/screw.cpp.i

.PHONY : rabbit/space/screw.i

# target to preprocess a source file
rabbit/space/screw.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit.dir/build.make submodules/rabbit/CMakeFiles/rabbit.dir/rabbit/space/screw.cpp.i
.PHONY : rabbit/space/screw.cpp.i

rabbit/space/screw.s: rabbit/space/screw.cpp.s

.PHONY : rabbit/space/screw.s

# target to generate assembly for a file
rabbit/space/screw.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit.dir/build.make submodules/rabbit/CMakeFiles/rabbit.dir/rabbit/space/screw.cpp.s
.PHONY : rabbit/space/screw.cpp.s

test/htrans3.o: test/htrans3.cpp.o

.PHONY : test/htrans3.o

# target to build an object file
test/htrans3.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/htrans3.cpp.o
.PHONY : test/htrans3.cpp.o

test/htrans3.i: test/htrans3.cpp.i

.PHONY : test/htrans3.i

# target to preprocess a source file
test/htrans3.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/htrans3.cpp.i
.PHONY : test/htrans3.cpp.i

test/htrans3.s: test/htrans3.cpp.s

.PHONY : test/htrans3.s

# target to generate assembly for a file
test/htrans3.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/htrans3.cpp.s
.PHONY : test/htrans3.cpp.s

test/intersect.o: test/intersect.cpp.o

.PHONY : test/intersect.o

# target to build an object file
test/intersect.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/intersect.cpp.o
.PHONY : test/intersect.cpp.o

test/intersect.i: test/intersect.cpp.i

.PHONY : test/intersect.i

# target to preprocess a source file
test/intersect.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/intersect.cpp.i
.PHONY : test/intersect.cpp.i

test/intersect.s: test/intersect.cpp.s

.PHONY : test/intersect.s

# target to generate assembly for a file
test/intersect.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/intersect.cpp.s
.PHONY : test/intersect.cpp.s

test/line2.o: test/line2.cpp.o

.PHONY : test/line2.o

# target to build an object file
test/line2.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/line2.cpp.o
.PHONY : test/line2.cpp.o

test/line2.i: test/line2.cpp.i

.PHONY : test/line2.i

# target to preprocess a source file
test/line2.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/line2.cpp.i
.PHONY : test/line2.cpp.i

test/line2.s: test/line2.cpp.s

.PHONY : test/line2.s

# target to generate assembly for a file
test/line2.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/line2.cpp.s
.PHONY : test/line2.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

test/nearest.o: test/nearest.cpp.o

.PHONY : test/nearest.o

# target to build an object file
test/nearest.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/nearest.cpp.o
.PHONY : test/nearest.cpp.o

test/nearest.i: test/nearest.cpp.i

.PHONY : test/nearest.i

# target to preprocess a source file
test/nearest.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/nearest.cpp.i
.PHONY : test/nearest.cpp.i

test/nearest.s: test/nearest.cpp.s

.PHONY : test/nearest.s

# target to generate assembly for a file
test/nearest.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/nearest.cpp.s
.PHONY : test/nearest.cpp.s

test/optimize.o: test/optimize.cpp.o

.PHONY : test/optimize.o

# target to build an object file
test/optimize.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/optimize.cpp.o
.PHONY : test/optimize.cpp.o

test/optimize.i: test/optimize.cpp.i

.PHONY : test/optimize.i

# target to preprocess a source file
test/optimize.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/optimize.cpp.i
.PHONY : test/optimize.cpp.i

test/optimize.s: test/optimize.cpp.s

.PHONY : test/optimize.s

# target to generate assembly for a file
test/optimize.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/optimize.cpp.s
.PHONY : test/optimize.cpp.s

test/pose3.o: test/pose3.cpp.o

.PHONY : test/pose3.o

# target to build an object file
test/pose3.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/pose3.cpp.o
.PHONY : test/pose3.cpp.o

test/pose3.i: test/pose3.cpp.i

.PHONY : test/pose3.i

# target to preprocess a source file
test/pose3.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/pose3.cpp.i
.PHONY : test/pose3.cpp.i

test/pose3.s: test/pose3.cpp.s

.PHONY : test/pose3.s

# target to generate assembly for a file
test/pose3.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/pose3.cpp.s
.PHONY : test/pose3.cpp.s

test/svd.o: test/svd.cpp.o

.PHONY : test/svd.o

# target to build an object file
test/svd.cpp.o:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/svd.cpp.o
.PHONY : test/svd.cpp.o

test/svd.i: test/svd.cpp.i

.PHONY : test/svd.i

# target to preprocess a source file
test/svd.cpp.i:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/svd.cpp.i
.PHONY : test/svd.cpp.i

test/svd.s: test/svd.cpp.s

.PHONY : test/svd.s

# target to generate assembly for a file
test/svd.cpp.s:
	cd /home/mirmik/project/radioline/rfmeask && $(MAKE) -f submodules/rabbit/CMakeFiles/rabbit_test.dir/build.make submodules/rabbit/CMakeFiles/rabbit_test.dir/test/svd.cpp.s
.PHONY : test/svd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... install/local"
	@echo "... rabbit"
	@echo "... rabbit_test"
	@echo "... rabbit/intersect.o"
	@echo "... rabbit/intersect.i"
	@echo "... rabbit/intersect.s"
	@echo "... rabbit/space/screw.o"
	@echo "... rabbit/space/screw.i"
	@echo "... rabbit/space/screw.s"
	@echo "... test/htrans3.o"
	@echo "... test/htrans3.i"
	@echo "... test/htrans3.s"
	@echo "... test/intersect.o"
	@echo "... test/intersect.i"
	@echo "... test/intersect.s"
	@echo "... test/line2.o"
	@echo "... test/line2.i"
	@echo "... test/line2.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/nearest.o"
	@echo "... test/nearest.i"
	@echo "... test/nearest.s"
	@echo "... test/optimize.o"
	@echo "... test/optimize.i"
	@echo "... test/optimize.s"
	@echo "... test/pose3.o"
	@echo "... test/pose3.i"
	@echo "... test/pose3.s"
	@echo "... test/svd.o"
	@echo "... test/svd.i"
	@echo "... test/svd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/mirmik/project/radioline/rfmeask && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

